### ISSUE TITLE
Will it support my whole react projects ?

### ISSUE THREAD

**Issue by TheRakeshPurohit** [dwjohnston/sass-compiler-api#2]
I have to implement as my dedicated scss to css compiler ! all my scss including mixins, imports, etc. with multiple files. will it work that way ??

**Comment by dwjohnston** [comment]
I don't know. 

If you look at the code, this is just an express wrapper around [node-sass](https://github.com/sass/node-sass). So I would read the documentation there to see what node-sass is and isn't capable of. 

But basically this is just 'turn this string of sass into this string of css'. So in terms of if you were referencing other files etc, probably not? But maybe you can fork and edit the code yourself to make it fit for purpose.
